package.json
=> [RFR] Fix dependencies

src/actions/PetitionActions.js, src/assets/styles/_globals.scss, src/components/Petitions/index.js, src/containers/Petition.js, src/containers/Petitions.js, src/helpers/calculateParamOffset.js, src/helpers/getPetitionsRequestParams.js, src/helpers/sanitizeParamLimit.js, src/reducers/petition.js, src/reducers/petitions.js, src/selectors/petitionEndDate.js, src/selectors/petitionTeaser.js, src/server/getBrowserTitle.js, src/services/api/repositories/petition.js, src/settings/config.js, test/helpers/calculateParamOffset.js, test/helpers/getPetitionsRequestParams.js, test/helpers/sanitizeParamLimit.js, test/services/api/repositories/petition.js
@sigmarstern added some sanitization to the `page` and `limit` params with tests. giving negative numbers for each was giving an errror.
=> [WIP] Petitions review

src/components/LoginLink/index.js, src/routes.js, src/services/api/repositories/auth.js, src/services/auth/Logout.js, src/services/auth/index.js, src/views/Home.js, test/services/api/repositories/auth.js
@mattberridge, @artibella  Look at this! A login/logout link component!
=> [RFR] Add Logout Link

src/components/Login/index.js, src/components/Login/login.scss, src/containers/Login.js, src/settings/config.js
Abstracting presentational and container component for the Login page, with translations
=> [RFR] Login container

package.json
This solves an issue where was Heroku refusing to build although all checks passed
=> Disable webpack build progress

src/containers/Petition.js, src/selectors/petition.js
=> [RFR] Refactor PetitionContainer to have all petition data in place

src/components/FormField/form-field.scss, src/components/FormField/index.js, src/components/FormFieldWrapper/form-field-wrapper.scss, src/components/FormFieldWrapper/index.js, src/components/PetitionForm/index.js, src/settings/config.js
Ping @Tom-Bonnike 
Abstracts the field and the wrapper via a higher-order component
=> [RFR] Abstract FormFieldWrapper to HOC

src/actions/PetitionActions.js, src/assets/styles/_layout.scss, src/components/CreatePetition/index.js, src/components/Fieldset/fieldset.scss, src/components/FormWrapper/form-wrapper.scss, src/components/FormWrapper/index.js, src/components/PetitionBody/index.js, src/components/Teaser/teaser.scss, src/helpers/calculatePercentage.js, src/helpers/getPetitionDateRange.js, src/helpers/getPetitionDaysRemaining.js, src/helpers/getPetitionsRequestParams.js, src/reducers/petition.js, src/services/api/repositories/city.js, src/settings/config.js, src/theme/styles/_typography.scss, test/helpers/calculatePercentage.js, test/helpers/getPetitionDaysRemaining.js, test/helpers/getPetitionsRequestParams.js, test/services/api/repositories/city.js, test/services/api/repositories/petition.js
=> Sprint Review

src/components/Autocomplete/index.js, src/components/CheckAuth/index.js, src/components/CircleProgressBar/circleprogressbar.scss, src/components/CircleProgressBar/index.js, src/components/Loading/index.js, src/components/PetitionForm/fields.js, src/components/Petitions/index.js, src/containers/Login.js, src/containers/Petition.js, src/containers/Petitions.js, src/containers/Restricted.js, src/reducers/petition.js, src/reducers/petitions.js, src/selectors/petitionCity.js, test/reducers/petition.js, test/reducers/petitions.js, test/selectors/petitionCity.js
Bug fixes we found in the review plus some other improvements:
- Tweak client-side loading of Petition and Petitions
- Add loading screen and (`<Loading>` component) to Petition and Petitions when redux is performing actions
=> [RFR] Sprint 4 Fixes

src/routes.js
Visit https://iris-frontend-staging-pr-70.herokuapp.com, see list of petitions as home page.
Old "home" still at https://iris-frontend-staging-pr-70.herokuapp.com/home
=> use /petitions view as the default homepage

src/components/PetitionForm/fields.js, src/containers/Autocomplete.js, src/containers/EditPetition.js, src/views/Home.js
Making this for changes or improvements made to the Create / Edit / Publish Petition flow
=> [WIP] Petition Flow Tweaks

src/assets/styles/base.scss
Link color as seen [here](https://app.zeplin.io/project.html#pid=57a32028382024014bb4f3b5&sid=57cd55bbc8057a6c67a73e46)
=> [RFR] Tertiary blue as global link style

src/components/Pagination/index.js, test/components/Pagination.js
Enzyme has a straightforward shallow-render method to use w/ Chai. Might as well...
=> [RFR] Pagination unit test

src/components/ButtonLink/index.js, src/components/Link/index.js, src/components/PetitionLink/index.js, src/containers/EditPetition.js, src/containers/NewPetition.js, src/containers/PublishedPetition.js, src/helpers/getPetitionLink.js, src/helpers/getPetitionPath.js, src/helpers/getPetitionURL.js, src/helpers/getSupportedPetitionModal.js, src/selectors/petitionPath.js
@mattberridge @pgoetze @eschaefer 
Solution so that Links always are a react-router link if they’re not external, and that styles are shared. Tell me what you think.
=> [RFR] Reworked custom Link component to allow react-router links to be used

src/containers/Petition.js
Supporting was broken, so I fixed it :)
=> [RFR] Fix supporting intent

src/services/api/repositories/petition.js, test/services/api/repositories/petition.js
Need this for response form to be submitted.
=> [RFR] Fix petition API request 

src/components/PetitionSidebar/index.js, src/components/PetitionSupportButton/index.js, src/containers/SharePetition.js, src/helpers/sharing/generateShareButtons.js, src/helpers/sharing/getPetitionEmailBody.js, src/helpers/sharing/getPetitionEmailSubject.js, src/helpers/sharing/getPetitionTweetText.js, src/settings/config.js, test/helpers/sharing/getPetitionEmailBody.js, test/helpers/sharing/getPetitionEmailSubject.js, test/helpers/sharing/getPetitionTweetText.js, test/mocks/city.json, test/mocks/petitionWithoutCity.json
=> [RFR] Add city and title to sharing

src/components/Button/button.scss, src/components/ModalIntro/index.js, src/components/ModalWindow/index.js, src/components/ModalWindow/modal-window.scss, src/components/Overlay/index.js, src/components/TrustConfirmation/index.js, src/components/TrustConfirmationForm/index.js, src/components/TrustForm/index.js, src/containers/TrustConfirmation.js, src/selectors/trustForm.js
Styling and copy coming later!
=> [RFR] "Go back" steps in Trust flow

src/actions/PetitionActions.js, src/components/ExternalTeaser/index.js, src/components/ExternalTeaserBlock/external-teaser-block.scss, src/components/ExternalTeaserBlock/index.js, src/components/PetitionFooter/index.js, src/containers/PetitionFooter.js, src/services/api/repositories/petition.js, src/settings/config.js, test/services/api/repositories/petition.js
This shows the article teasers of a petition
can be testet with petition with ID `1lcVp`
=> [RFR] #75 Show connected articles of a petition

package.json, src/routes.js
Using https://github.com/taion/react-router-scroll to achieve default browser behavior when changing routes client-side.
=> [RFR] Fix scroll behavior

src/form/fieldIsValid.js, test/form/fieldIsValid.js
Tweak validation helper to allow valid icon to be shown when forms are pre-filled with data, either after sign-in via SSO or when editing a petition
=> [RFR] Confirm pre-filled data

src/components/Trust/index.js, src/containers/PreviewPetition.js, src/containers/RedirectIfPublished.js, src/containers/RedirectIfUnsupportable.js, src/containers/TrustPublish.js, src/containers/TrustSupport.js
Fix for: https://trello.com/c/zQTozKQQ/202-202-iris-login-must-work-via-sso-via-oauth-3-sprint8#comment-58165d9b3dcdd288523e6750
=> [RFM] Fix SSO return URL

package.json, scripts/update.sh
More to do later, but upgrade now works from `develop` to new branch
=> [RFM] Fix upgrade script

src/theme/translations.js
some new translation keys were not quoted. As we need a JSON compatible format for the translation tool I quickly added the missing quotes for the key.
=> [RFR] Make translation keys JSON compatible

.env.default, README.md
- Restructure `README.md`
- Include information on how to fork, update and customize the project
- Add helpful comments to `.env.default`
=> Update and restructure README.md
